version: '3.7'

services:
  selenium:
    image: selenium/standalone-chrome-debug:3.141.59
    ports:
    - 4444:4444
    volumes:
    # Workaround to avoid the browser crashing inside a docker container
    # See https://github.com/SeleniumHQ/docker-selenium#quick-start
    - /dev/shm:/dev/shm
    restart: unless-stopped

  scraper:
    build: .
    depends_on:
      - selenium
    volumes:
      - ./screenshots:/app/screenshots


  